### ISSUE TITLE
Operations not working + Add string storage to /execute subcommands

### ISSUE THREAD

**Issue by fennecr** [fafik77/Mc_Data_Concat-1.20#1]
![image](https://github.com/user-attachments/assets/5743c039-34ab-4f57-804d-fd5816691294)
![image](https://github.com/user-attachments/assets/ea3fc359-5a58-40e0-b7a6-8ed938f0dc7c)

First of all, I can't seem to figure out operations on existing data, it allows me to specify that I want to use operation but not which one (see first screenshot)
Second, it would be great to have access to string storage from /execute store, such as /execute store result storageplayer @s path **string**

**Comment by fafik77** [comment]
`/data modify storageplayer @s storage operation (=, +=, -=, *=, /=, %=, ^=, <, > )` in this context operation means Math operation, numbers can not be concatenated.
To concatenate strings use `/data modify storageplayer @s testOut set concat storageplayer @s testIn`
**Works as intended**

Second `/execute store result` and `/execute store success` only work with integers, providing a string to it will only return its length
**Works as intended**

Documentation has been updated and is available on https://modrinth.com/mod/data-command-plus
